(cl:defpackage human_navigation-msg
  (:use )
  (:export
   "<HUMANNAVIAVATARSTATUS>"
   "HUMANNAVIAVATARSTATUS"
   "<HUMANNAVIDESTINATION>"
   "HUMANNAVIDESTINATION"
   "<HUMANNAVIGUIDANCEMSG>"
   "HUMANNAVIGUIDANCEMSG"
   "<HUMANNAVIMSG>"
   "HUMANNAVIMSG"
   "<HUMANNAVIOBJECTINFO>"
   "HUMANNAVIOBJECTINFO"
   "<HUMANNAVIOBJECTSTATUS>"
   "HUMANNAVIOBJECTSTATUS"
   "<HUMANNAVITASKINFO>"
   "HUMANNAVITASKINFO"
  ))

