// Auto-generated. Do not edit!

// (in-package darknet_ros_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let BoundingBoxes = require('./BoundingBoxes.js');

//-----------------------------------------------------------

class CheckForObjectsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.id = null;
      this.boundingBoxes = null;
    }
    else {
      if (initObj.hasOwnProperty('id')) {
        this.id = initObj.id
      }
      else {
        this.id = 0;
      }
      if (initObj.hasOwnProperty('boundingBoxes')) {
        this.boundingBoxes = initObj.boundingBoxes
      }
      else {
        this.boundingBoxes = new BoundingBoxes();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CheckForObjectsResult
    // Serialize message field [id]
    bufferOffset = _serializer.int16(obj.id, buffer, bufferOffset);
    // Serialize message field [boundingBoxes]
    bufferOffset = BoundingBoxes.serialize(obj.boundingBoxes, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CheckForObjectsResult
    let len;
    let data = new CheckForObjectsResult(null);
    // Deserialize message field [id]
    data.id = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [boundingBoxes]
    data.boundingBoxes = BoundingBoxes.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += BoundingBoxes.getMessageSize(object.boundingBoxes);
    return length + 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'darknet_ros_msgs/CheckForObjectsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b7095776bbf2dd52b93a4ce86a7902c0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result definition
    int16 id
    darknet_ros_msgs/BoundingBoxes boundingBoxes
    
    
    ================================================================================
    MSG: darknet_ros_msgs/BoundingBoxes
    Header header
    BoundingBox[] boundingBoxes
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: darknet_ros_msgs/BoundingBox
    string Class
    float64 probability
    int64 xmin
    int64 ymin
    int64 xmax
    int64 ymax
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CheckForObjectsResult(null);
    if (msg.id !== undefined) {
      resolved.id = msg.id;
    }
    else {
      resolved.id = 0
    }

    if (msg.boundingBoxes !== undefined) {
      resolved.boundingBoxes = BoundingBoxes.Resolve(msg.boundingBoxes)
    }
    else {
      resolved.boundingBoxes = new BoundingBoxes()
    }

    return resolved;
    }
};

module.exports = CheckForObjectsResult;
