# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from human_navigation/HumanNaviTaskInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import human_navigation.msg

class HumanNaviTaskInfo(genpy.Message):
  _md5sum = "72a83c8dcb8252f4b5e97040679254a7"
  _type = "human_navigation/HumanNaviTaskInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string environment_id
HumanNaviObjectInfo target_object
HumanNaviDestination destination
HumanNaviObjectInfo[] non_target_objects
HumanNaviObjectInfo[] furniture

================================================================================
MSG: human_navigation/HumanNaviObjectInfo
string name
geometry_msgs/Point position
geometry_msgs/Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: human_navigation/HumanNaviDestination
geometry_msgs/Point position
geometry_msgs/Quaternion orientation
geometry_msgs/Point size
"""
  __slots__ = ['environment_id','target_object','destination','non_target_objects','furniture']
  _slot_types = ['string','human_navigation/HumanNaviObjectInfo','human_navigation/HumanNaviDestination','human_navigation/HumanNaviObjectInfo[]','human_navigation/HumanNaviObjectInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       environment_id,target_object,destination,non_target_objects,furniture

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanNaviTaskInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.environment_id is None:
        self.environment_id = ''
      if self.target_object is None:
        self.target_object = human_navigation.msg.HumanNaviObjectInfo()
      if self.destination is None:
        self.destination = human_navigation.msg.HumanNaviDestination()
      if self.non_target_objects is None:
        self.non_target_objects = []
      if self.furniture is None:
        self.furniture = []
    else:
      self.environment_id = ''
      self.target_object = human_navigation.msg.HumanNaviObjectInfo()
      self.destination = human_navigation.msg.HumanNaviDestination()
      self.non_target_objects = []
      self.furniture = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.environment_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.target_object.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_17d().pack(_x.target_object.position.x, _x.target_object.position.y, _x.target_object.position.z, _x.target_object.orientation.x, _x.target_object.orientation.y, _x.target_object.orientation.z, _x.target_object.orientation.w, _x.destination.position.x, _x.destination.position.y, _x.destination.position.z, _x.destination.orientation.x, _x.destination.orientation.y, _x.destination.orientation.z, _x.destination.orientation.w, _x.destination.size.x, _x.destination.size.y, _x.destination.size.z))
      length = len(self.non_target_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.non_target_objects:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.furniture)
      buff.write(_struct_I.pack(length))
      for val1 in self.furniture:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v3 = val1.position
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v4 = val1.orientation
        _x = _v4
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.target_object is None:
        self.target_object = human_navigation.msg.HumanNaviObjectInfo()
      if self.destination is None:
        self.destination = human_navigation.msg.HumanNaviDestination()
      if self.non_target_objects is None:
        self.non_target_objects = None
      if self.furniture is None:
        self.furniture = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.environment_id = str[start:end].decode('utf-8')
      else:
        self.environment_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_object.name = str[start:end].decode('utf-8')
      else:
        self.target_object.name = str[start:end]
      _x = self
      start = end
      end += 136
      (_x.target_object.position.x, _x.target_object.position.y, _x.target_object.position.z, _x.target_object.orientation.x, _x.target_object.orientation.y, _x.target_object.orientation.z, _x.target_object.orientation.w, _x.destination.position.x, _x.destination.position.y, _x.destination.position.z, _x.destination.orientation.x, _x.destination.orientation.y, _x.destination.orientation.z, _x.destination.orientation.w, _x.destination.size.x, _x.destination.size.y, _x.destination.size.z,) = _get_struct_17d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.non_target_objects = []
      for i in range(0, length):
        val1 = human_navigation.msg.HumanNaviObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _v5 = val1.position
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v6 = val1.orientation
        _x = _v6
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.non_target_objects.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.furniture = []
      for i in range(0, length):
        val1 = human_navigation.msg.HumanNaviObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.furniture.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.environment_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.target_object.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_17d().pack(_x.target_object.position.x, _x.target_object.position.y, _x.target_object.position.z, _x.target_object.orientation.x, _x.target_object.orientation.y, _x.target_object.orientation.z, _x.target_object.orientation.w, _x.destination.position.x, _x.destination.position.y, _x.destination.position.z, _x.destination.orientation.x, _x.destination.orientation.y, _x.destination.orientation.z, _x.destination.orientation.w, _x.destination.size.x, _x.destination.size.y, _x.destination.size.z))
      length = len(self.non_target_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.non_target_objects:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v9 = val1.position
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = val1.orientation
        _x = _v10
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.furniture)
      buff.write(_struct_I.pack(length))
      for val1 in self.furniture:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v11 = val1.position
        _x = _v11
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v12 = val1.orientation
        _x = _v12
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.target_object is None:
        self.target_object = human_navigation.msg.HumanNaviObjectInfo()
      if self.destination is None:
        self.destination = human_navigation.msg.HumanNaviDestination()
      if self.non_target_objects is None:
        self.non_target_objects = None
      if self.furniture is None:
        self.furniture = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.environment_id = str[start:end].decode('utf-8')
      else:
        self.environment_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_object.name = str[start:end].decode('utf-8')
      else:
        self.target_object.name = str[start:end]
      _x = self
      start = end
      end += 136
      (_x.target_object.position.x, _x.target_object.position.y, _x.target_object.position.z, _x.target_object.orientation.x, _x.target_object.orientation.y, _x.target_object.orientation.z, _x.target_object.orientation.w, _x.destination.position.x, _x.destination.position.y, _x.destination.position.z, _x.destination.orientation.x, _x.destination.orientation.y, _x.destination.orientation.z, _x.destination.orientation.w, _x.destination.size.x, _x.destination.size.y, _x.destination.size.z,) = _get_struct_17d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.non_target_objects = []
      for i in range(0, length):
        val1 = human_navigation.msg.HumanNaviObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _v13 = val1.position
        _x = _v13
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v14 = val1.orientation
        _x = _v14
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.non_target_objects.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.furniture = []
      for i in range(0, length):
        val1 = human_navigation.msg.HumanNaviObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _v15 = val1.position
        _x = _v15
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v16 = val1.orientation
        _x = _v16
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.furniture.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_17d = None
def _get_struct_17d():
    global _struct_17d
    if _struct_17d is None:
        _struct_17d = struct.Struct("<17d")
    return _struct_17d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
