// Generated by gencpp from file human_navigation/HumanNaviDestination.msg
// DO NOT EDIT!


#ifndef HUMAN_NAVIGATION_MESSAGE_HUMANNAVIDESTINATION_H
#define HUMAN_NAVIGATION_MESSAGE_HUMANNAVIDESTINATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Point.h>

namespace human_navigation
{
template <class ContainerAllocator>
struct HumanNaviDestination_
{
  typedef HumanNaviDestination_<ContainerAllocator> Type;

  HumanNaviDestination_()
    : position()
    , orientation()
    , size()  {
    }
  HumanNaviDestination_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::human_navigation::HumanNaviDestination_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_navigation::HumanNaviDestination_<ContainerAllocator> const> ConstPtr;

}; // struct HumanNaviDestination_

typedef ::human_navigation::HumanNaviDestination_<std::allocator<void> > HumanNaviDestination;

typedef boost::shared_ptr< ::human_navigation::HumanNaviDestination > HumanNaviDestinationPtr;
typedef boost::shared_ptr< ::human_navigation::HumanNaviDestination const> HumanNaviDestinationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_navigation::HumanNaviDestination_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace human_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'human_navigation': ['/home/kamerider/sim_ws/src/human_navigation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviDestination_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviDestination_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviDestination_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9adffd11b4bc3effe2908e9f95d5bea";
  }

  static const char* value(const ::human_navigation::HumanNaviDestination_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9adffd11b4bc3efULL;
  static const uint64_t static_value2 = 0xfe2908e9f95d5beaULL;
};

template<class ContainerAllocator>
struct DataType< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_navigation/HumanNaviDestination";
  }

  static const char* value(const ::human_navigation::HumanNaviDestination_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
geometry_msgs/Quaternion orientation\n\
geometry_msgs/Point size\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::human_navigation::HumanNaviDestination_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanNaviDestination_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_navigation::HumanNaviDestination_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_navigation::HumanNaviDestination_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_NAVIGATION_MESSAGE_HUMANNAVIDESTINATION_H
