// Generated by gencpp from file interactive_cleanup/InteractiveCleanupMsg.msg
// DO NOT EDIT!


#ifndef INTERACTIVE_CLEANUP_MESSAGE_INTERACTIVECLEANUPMSG_H
#define INTERACTIVE_CLEANUP_MESSAGE_INTERACTIVECLEANUPMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interactive_cleanup
{
template <class ContainerAllocator>
struct InteractiveCleanupMsg_
{
  typedef InteractiveCleanupMsg_<ContainerAllocator> Type;

  InteractiveCleanupMsg_()
    : message()
    , detail()  {
    }
  InteractiveCleanupMsg_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _detail_type;
  _detail_type detail;





  typedef boost::shared_ptr< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> const> ConstPtr;

}; // struct InteractiveCleanupMsg_

typedef ::interactive_cleanup::InteractiveCleanupMsg_<std::allocator<void> > InteractiveCleanupMsg;

typedef boost::shared_ptr< ::interactive_cleanup::InteractiveCleanupMsg > InteractiveCleanupMsgPtr;
typedef boost::shared_ptr< ::interactive_cleanup::InteractiveCleanupMsg const> InteractiveCleanupMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interactive_cleanup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'interactive_cleanup': ['/home/kamerider/sim_ws/src/CleanUp/interactive_cleanup/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c3ad4b113aebdb7a85eba9ba595d50";
  }

  static const char* value(const ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c3ad4b113aebdbULL;
  static const uint64_t static_value2 = 0x7a85eba9ba595d50ULL;
};

template<class ContainerAllocator>
struct DataType< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interactive_cleanup/InteractiveCleanupMsg";
  }

  static const char* value(const ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
string detail\n\
";
  }

  static const char* value(const ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InteractiveCleanupMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interactive_cleanup::InteractiveCleanupMsg_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACTIVE_CLEANUP_MESSAGE_INTERACTIVECLEANUPMSG_H
